import Features from "../components/Features";
import Footer from "components/Footer";
import Head from "next/head";
import Intro from "../components/Intro";
import Navbar from "../components/common/Navbar";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Intro />
        <Features />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
