import Features from "../components/Features";
import Head from "next/head";
import Intro from "../components/Intro";
import Navbar from "../components/common/Navbar";
import type { NextPage } from "next";
import ShortenLink from "../components/ShortenLink";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <p className="title">bhjgg</p>
        <Button
          onClick={() => {
            console.log("Hi");
          }}
        >
          Click
        </Button> */}
        <Navbar />
        <Intro />
        <Features />
        <ShortenLink />
      </main>
    </div>
  );
};

export default Home;
